const V = '?v=2';

export const EXAM_DOCUMENTS = [
  {
    id: 'exam-1',
    title: '七年级数学期末检测',
    subtitle: '榆林市第六中学 2025-2026学年度第一学期',
    filename: '5NFfaS5PHSg81Ff2K20a8daY.jpg',
    thumb: '/exams/5NFfaS5PHSg81Ff2K20a8daY.jpg' + V,
    date: '2026/1/15',
    pages: 6,
    subject: '数学',
    grade: '七年级',
  },
  {
    id: 'exam-2',
    title: '数据的收集与整理 质量检测',
    subtitle: '第六章 统计学基础',
    filename: '7dHyKX2haYaA57aBFW694CAS.jpg',
    thumb: '/exams/7dHyKX2haYaA57aBFW694CAS.jpg' + V,
    date: '2026/3/20',
    pages: 4,
    subject: '数学',
    grade: '七年级',
  },
  {
    id: 'exam-3',
    title: '三年级语文全真模拟期末测试卷（一）',
    subtitle: '语文三年级下册',
    filename: '纯文本-739398.jpg',
    thumb: '/exams/纯文本-739398.jpg' + V,
    date: '2026/4/10',
    pages: 4,
    subject: '语文',
    grade: '三年级',
  },
  {
    id: 'exam-4',
    title: '初中毕业学业统一考试 生物',
    subtitle: '黑龙江省龙东地区 2022年',
    filename: '试卷作业_45365.jpg',
    thumb: '/exams/试卷作业_45365.jpg' + V,
    date: '2026/4/18',
    pages: 12,
    subject: '生物',
    grade: '初三',
  },
  {
    id: 'exam-5',
    title: '四年级语文下册期中情境素养测评',
    subtitle: '2025年期中测评',
    filename: 'C488hA2E866dtdLJA8E3J6We.jpg',
    thumb: '/exams/C488hA2E866dtdLJA8E3J6We.jpg' + V,
    date: '2026/4/25',
    pages: 6,
    subject: '语文',
    grade: '四年级',
    topics: ['看拼音写词语', '旅行寄语', '修改病句', '口语交际', '阅读理解', '选词填空'],
  },
  {
    id: 'exam-6',
    title: '三年级道德与法治上册期末押题试卷',
    subtitle: '期末押题试卷（二）',
    filename: '三年级道德与法治上册期末押题试卷(2)_ST9E5fHVfBrMDRDy2478TKBB_pdfx0.pdf',
    thumb: '/exams/三年级道德与法治_thumb-1.jpg' + V,
    date: '2026/5/10',
    pages: 10,
    subject: '道德与法治',
    grade: '三年级',
    topics: ['学习态度', '交通规则', '校园生活', '家庭关系', '传统文化'],
  },
];

export const EXAM_GRADABLE = ['exam-1', 'exam-2', 'exam-3', 'exam-4', 'exam-5', 'exam-6'];
