const V = '?v=2';

export const EXAM_DOCUMENTS = [
  {
    id: 'exam-1',
    title: '七年级数学期末检测',
    subtitle: '榆林市第六中学 2025-2026学年度第一学期',
    filename: '5NFfaS5PHSg81Ff2K20a8daY.jpg',
    thumb: '/exams/5NFfaS5PHSg81Ff2K20a8daY.jpg' + V,
    date: '2026/1/15',
    pages: 6,
    subject: '数学',
    grade: '七年级',
  },
  {
    id: 'exam-2',
    title: '数据的收集与整理 质量检测',
    subtitle: '第六章 统计学基础',
    filename: '7dHyKX2haYaA57aBFW694CAS.jpg',
    thumb: '/exams/7dHyKX2haYaA57aBFW694CAS.jpg' + V,
    date: '2026/3/20',
    pages: 4,
    subject: '数学',
    grade: '七年级',
  },
  {
    id: 'exam-3',
    title: '三年级语文全真模拟期末测试卷（一）',
    subtitle: '语文三年级下册',
    filename: '纯文本-739398.jpg',
    thumb: '/exams/纯文本-739398.jpg' + V,
    date: '2026/4/10',
    pages: 4,
    subject: '语文',
    grade: '三年级',
  },
  {
    id: 'exam-4',
    title: '初中毕业学业统一考试 生物',
    subtitle: '黑龙江省龙东地区 2022年',
    filename: '试卷作业_45365.jpg',
    thumb: '/exams/试卷作业_45365.jpg' + V,
    date: '2026/4/18',
    pages: 12,
    subject: '生物',
    grade: '初三',
  },
  {
    id: 'exam-5',
    title: '四年级语文下册期中情境素养测评',
    subtitle: '2025年期中测评',
    filename: 'C488hA2E866dtdLJA8E3J6We.jpg',
    thumb: '/exams/C488hA2E866dtdLJA8E3J6We.jpg' + V,
    date: '2026/4/25',
    pages: 6,
    subject: '语文',
    grade: '四年级',
    topics: ['看拼音写词语', '旅行寄语', '修改病句', '口语交际', '阅读理解', '选词填空'],
  },
  {
    id: 'exam-6',
    title: '三年级道德与法治上册期末押题试卷',
    subtitle: '期末押题试卷（二）',
    filename: '三年级道德与法治上册期末押题试卷(2)_ST9E5fHVfBrMDRDy2478TKBB_pdfx0.pdf',
    thumb: '/exams/三年级道德与法治_thumb-1.jpg' + V,
    date: '2026/5/10',
    pages: 10,
    subject: '道德与法治',
    grade: '三年级',
    topics: ['学习态度', '交通规则', '校园生活', '家庭关系', '传统文化'],
  },
];

export const CACHED_EXAM_RESULTS = {
  'exam-2': {
    questions: [
      { number: 1, content: '收集数据后，在描述数据时，为"显示部分在总体中所占的百分比"，适宜采用', correct: false, userAnswer: 'A', correctAnswer: 'B', options: ['条形统计图', '扇形统计图', '折线统计图', '直方统计图'], subject: '数学', topic: '统计图选择' },
      { number: 2, content: '为了了解某地区老年人的健康状况，分别给了4种不同的抽样方案，你认为抽样比较合理的是', correct: true, userAnswer: 'D', correctAnswer: 'D', options: ['在公园里调查1000名老年人', '在医院调查1000名老年人', '随机调查10名老年人', '利用派出所户籍随机调查10%的老年人'], subject: '数学', topic: '抽样方法' },
      { number: 3, content: '调查下列问题，适合采用全面调查(普查)的是', correct: false, userAnswer: 'D', correctAnswer: 'C', options: ['有内蒙居民对"河南两会"的关注度', '了解某批新疆大枣的合格率', '检测"神舟十八号"飞船的零件', '检测洛阳的城市空气质量'], subject: '数学', topic: '普查与抽样' },
      { number: 4, content: '为了了解某1500名学生的体质健康状况，从中抽取100名学生进行体检，下面说法正确的是', correct: true, userAnswer: 'D', correctAnswer: 'D', options: ['1500名学生的体重是总体', '样本容量为1500', '每个学生是个体', '100名学生是所抽取的一个样本'], subject: '数学', topic: '总体与样本' },
      { number: 5, content: '如图是一所学校对学生上学方式进行调查后，根据调查结果绘制的统计图，其中"其他"部分对应的圆心角为', correct: false, userAnswer: 'A', correctAnswer: 'B', options: ['40°', '36°', '30°', '45°'], subject: '数学', topic: '扇形统计图' },
      { number: 6, content: '下列调查中，调查方式选择正确的是', correct: true, userAnswer: 'B', correctAnswer: 'B', options: ['调查全国中学生视力用普查', '央视某节目收视率用抽样调查', '调查某班学生身高用抽样调查', '了解某批药品质量用普查'], subject: '数学', topic: '调查方式' },
      { number: 7, content: '相邻两期数据集中，第2期与第3期两次人数试验的比是均匀的，下列调查方式你认为合适的是', correct: false, userAnswer: 'A', correctAnswer: 'C', options: ['全面调查所有居民', '随机调查10人', '采大众城市统计', '网络投票调查'], subject: '数学', topic: '数据收集方法' },
      { number: 8, content: '2024年某中学四年级4个班的学生去到光公园义务植树，已知各班人数统计图，各班学生人数频率分布为', correct: true, userAnswer: 'C', correctAnswer: 'C', options: ['5', '6', '7', '8'], subject: '数学', topic: '频率分布' },
      { number: 9, content: '若已知所示的频数直方图，其中组别为99.5-124.5这一组的频数为', correct: false, userAnswer: 'A', correctAnswer: 'B', options: ['5', '6', '7', '8'], subject: '数学', topic: '频数直方图' },
      { number: 10, content: '共有500名学生参加知识竞赛，某校三月份和五月份先进学生人数统计图如图，分析正确的是', correct: true, userAnswer: 'C', correctAnswer: 'C', options: ['三月先进人数比五月多', '五月先进人数总体增加', '各类先进人数五月均多于三月', '无法判断变化趋势'], subject: '数学', topic: '统计图分析' },
    ]
  },
  'exam-1': {
    questions: [
      { number: 1, content: '-5的倒数是', correct: true, userAnswer: 'A', correctAnswer: 'A', options: ['-1/5', '-5', '1/5', '5'], subject: '数学', topic: '有理数' },
      { number: 2, content: '高速公路在建设过程中需要从大山中开凿隧道或沿山壁开辟通路，其中桥遂数量最多的是哪条路', correct: false, userAnswer: 'B', correctAnswer: 'C', options: ['沪昆高速', '京港澳高速', '沪蓉高速', '兰海高速'], subject: '数学', topic: '数据分析' },
      { number: 3, content: '248300用科学记数法表示为', correct: true, userAnswer: 'D', correctAnswer: 'D', options: ['4.83×10⁵', '24.83×10⁴', '0.2483×10⁶', '2.483×10⁵'], subject: '数学', topic: '科学记数法' },
      { number: 4, content: '下列图形中，只有一个是从正面看到的形状图形对应的立体图形，请判别', correct: false, userAnswer: 'A', correctAnswer: 'B', options: ['圆柱', '三棱柱', '圆锥', '长方体'], subject: '数学', topic: '空间图形' },
      { number: 5, content: '已知∠A=31°47′，则∠A的补角的度数为', correct: true, userAnswer: 'D', correctAnswer: 'D', options: ['88°53′', '148°55′', '59°13′', '148°13′'], subject: '数学', topic: '角的计算' },
      { number: 6, content: '点M是线段AC的中点，在线段CB上一点N，使得CN=CB/4，若AC=6cm，BC=8cm，则MN的长为', correct: false, userAnswer: 'A', correctAnswer: 'B', options: ['5cm', '6cm', '7cm', '4.5cm'], subject: '数学', topic: '线段中点' },
      { number: 7, content: '日历牌上"H"型框覆盖任七个数，它们的和可能是', correct: true, userAnswer: 'A', correctAnswer: 'A', options: ['189', '126', '112', '85'], subject: '数学', topic: '规律探究' },
      { number: 8, content: '有理数a,b在数轴上对应点的位置如图所示，下列结论正确的是', correct: false, userAnswer: 'A', correctAnswer: 'C', options: ['a+b>0', 'a-b<0', 'ab>0', 'a/b>0'], subject: '数学', topic: '数轴与有理数' },
      { number: 9, content: '金漆木雕工艺要求精准控制雕刻深度，标准值4mm，上下浮动不超过0.05mm，则测量值合格的是', correct: true, userAnswer: 'D', correctAnswer: 'D', options: ['+0.1mm', '-0.06mm', '+0.052mm', '-0.04mm'], subject: '数学', topic: '绝对值应用' },
      { number: 10, content: '如图L₁∥L₂，∠1=∠2，已知∠3=70°，求∠1的度数', correct: false, userAnswer: 'B', correctAnswer: 'C', options: ['30°', '35°', '70°', '110°'], subject: '数学', topic: '平行线性质' },
      { number: 11, content: '在长方形ABCD中，∠ABC=90°，BD为对角线，∠ABD的角平分线BF交AD于F，求∠EBF的度数', correct: true, userAnswer: 'B', correctAnswer: 'B', options: ['25°', '30°', '35°', '45°'], subject: '数学', topic: '角平分线' },
      { number: 12, content: '某科技小组用相同基本图形按规律拼接菱形图形，第15步需要的基本图形个数为', correct: false, userAnswer: 'C', correctAnswer: 'B', options: ['61', '57', '53', '49'], subject: '数学', topic: '图形规律' },
      { number: 13, content: '一个水池，单开甲管2.5小时注满，单开乙管需要几小时注满，甲乙注水速度比为2:3', correct: true, userAnswer: 'A', correctAnswer: 'A', options: ['2:3', '3:2', '1:2', '2:1'], subject: '数学', topic: '一元一次方程应用' },
      { number: 14, content: '计算：(-1)³+6×(-1/2)²-2×|-4|', correct: false, userAnswer: 'B', correctAnswer: 'D', options: ['-7', '-7.5', '-8', '-7.5'], subject: '数学', topic: '有理数混合运算' },
      { number: 15, content: '计算：1+(-4)-(-6)', correct: true, userAnswer: 'C', correctAnswer: 'C', options: ['-1', '1', '3', '11'], subject: '数学', topic: '有理数加减' },
    ]
  },
  'exam-3': {
    questions: [
      { number: 1, content: '给加点字选择正确的读音：鲜艳', correct: true, userAnswer: 'A', correctAnswer: 'A', options: ['xiān', 'xiǎn'], subject: '语文', topic: '拼音辨析' },
      { number: 2, content: '给加点字选择正确的读音：折腾', correct: true, userAnswer: 'A', correctAnswer: 'A', options: ['zhē', 'zhé'], subject: '语文', topic: '多音字' },
      { number: 3, content: '给加点字选择正确的读音：夹袄', correct: true, userAnswer: 'B', correctAnswer: 'B', options: ['jiā', 'jiá'], subject: '语文', topic: '多音字' },
      { number: 4, content: '给加点字选择正确的读音：蚂蚱', correct: true, userAnswer: 'B', correctAnswer: 'B', options: ['mǎ', 'mà'], subject: '语文', topic: '多音字' },
      { number: 5, content: '给加点字选择正确的读音：石缝', correct: true, userAnswer: 'B', correctAnswer: 'B', options: ['féng', 'fèng'], subject: '语文', topic: '多音字' },
      { number: 6, content: '给加点字选择正确的读音：都城', correct: true, userAnswer: 'A', correctAnswer: 'A', options: ['dū', 'dōu'], subject: '语文', topic: '多音字' },
      { number: 7, content: '看拼音写字词：líng lì（伶俐）', correct: true, userAnswer: '伶俐', correctAnswer: '伶俐', subject: '语文', topic: '看拼音写词语' },
      { number: 8, content: '看拼音写字词：nuò ruò（懦弱）', correct: false, userAnswer: '诺弱', correctAnswer: '懦弱', subject: '语文', topic: '看拼音写词语' },
      { number: 9, content: '看拼音写字词：xiān xì（纤细）', correct: true, userAnswer: '纤细', correctAnswer: '纤细', subject: '语文', topic: '看拼音写词语' },
      { number: 10, content: '看拼音写字词：biàn rèn（辨认）', correct: true, userAnswer: '辨认', correctAnswer: '辨认', subject: '语文', topic: '看拼音写词语' },
      { number: 11, content: '看拼音写字词：tóng fú（童服）', correct: true, userAnswer: '童服', correctAnswer: '童服', subject: '语文', topic: '看拼音写词语' },
      { number: 12, content: '看拼音写字词：chéng xiàn（呈现）', correct: true, userAnswer: '呈现', correctAnswer: '呈现', subject: '语文', topic: '看拼音写词语' },
      { number: 13, content: '下列各组词语中，读音或字形完全正确的一组是', correct: true, userAnswer: 'B', correctAnswer: 'B', options: ['勾称(chèn)　一乘(chéng)轿子　欧洲　通情达理', '积累(lěi)　情不自禁(jìn)　干燥　没精打采', '拂晓　虎视眈眈', '干燥　没精打采'], subject: '语文', topic: '字词辨析' },
      { number: 14, content: '"这首曲子越听越有味儿"中，"味儿"的意思是', correct: true, userAnswer: 'C', correctAnswer: 'C', options: ['气味', '意味、趣味', '滋味', '体会、研究'], subject: '语文', topic: '词义理解' },
      { number: 15, content: '我和他成为好朋友后，受他影响，我也爱上了学习。这正是( )', correct: true, userAnswer: 'C', correctAnswer: 'C', options: ['近朱者赤，近墨者黑', '三而不改，是谓过矣', '眼见为实，耳听为虚', '过而能改，善莫大焉'], subject: '语文', topic: '俗语运用' },
      { number: 16, content: '下列传统节日与习俗对应错误的一项是', correct: true, userAnswer: 'C', correctAnswer: 'C', options: ['元宵节：猜灯谜，吃元宵', '中秋节：赏月，登高', '端午节：吃粽子，赛龙舟', '清明节：扫墓祭祖，踏青'], subject: '语文', topic: '传统文化' },
    ]
  },
  'exam-4': {
    questions: [
      { number: 1, content: '春暖花开，万物复苏，到处呈现出生机勃勃的景象。下列属于生物的是', correct: true, userAnswer: 'C', correctAnswer: 'C', options: ['机器人在弹钢琴', '钟乳石在慢慢长大', '生石花开出黄色的花朵', '导航里帮我们规划路线的小度'], subject: '生物', topic: '生物特征' },
      { number: 2, content: '生态系统多种多样，其中有"地球之肾"之称的生态系统是', correct: false, userAnswer: 'D', correctAnswer: 'B', options: ['草原生态系统', '湿地生态系统', '农田生态系统', '森林生态系统'], subject: '生物', topic: '生态系统类型' },
      { number: 3, content: '在小麦田中有一条食物链，如果此麦田被难以分解的农药污染，则体内农药积累含量最高的是', correct: true, userAnswer: 'D', correctAnswer: 'D', options: ['小麦', '蚜虫', '七星瓢虫', '食虫鸟'], subject: '生物', topic: '食物链与生物富集' },
      { number: 4, content: '我国已开展全民义务植树活动40余年，森林覆盖率提高到21.63%，既改善了空气质量，又增加了降水量，这说明了', correct: false, userAnswer: 'C', correctAnswer: 'A', options: ['生物影响环境', '环境影响生物', '生物适应环境', '环境适应生物'], subject: '生物', topic: '生物与环境' },
      { number: 5, content: '下列关于生物圈的说法，正确的是', correct: true, userAnswer: 'B', correctAnswer: 'B', options: ['生物圈是指地球上所有生物', '生物圈是最大的生态系统', '生物圈只包括大气圈', '生物圈中各生态系统互不相关'], subject: '生物', topic: '生态系统类型' },
      { number: 6, content: '用显微镜观察人体口腔上皮细胞时，染色常用的液体是', correct: true, userAnswer: 'A', correctAnswer: 'A', options: ['碘液', '生理盐水', '清水', '酒精'], subject: '生物', topic: '显微镜使用' },
      { number: 7, content: '植物体的结构层次从微观到宏观依次是', correct: false, userAnswer: 'B', correctAnswer: 'C', options: ['组织→细胞→器官→植物体', '细胞→器官→组织→植物体', '细胞→组织→器官→植物体', '器官→组织→细胞→植物体'], subject: '生物', topic: '生物体结构层次' },
      { number: 8, content: '下列食物链正确的是', correct: true, userAnswer: 'C', correctAnswer: 'C', options: ['阳光→草→兔→鹰', '草←兔←鹰', '草→兔→鹰', '兔→草→鹰'], subject: '生物', topic: '食物链与生物富集' },
      { number: 9, content: '"螳螂捕蝉，黄雀在后"描述的是生物之间的关系是', correct: true, userAnswer: 'A', correctAnswer: 'A', options: ['捕食关系', '竞争关系', '合作关系', '寄生关系'], subject: '生物', topic: '生物关系' },
      { number: 10, content: '含羞草受到触碰后叶片合拢，这说明生物具有的特征是', correct: true, userAnswer: 'B', correctAnswer: 'B', options: ['生物能生长和繁殖', '对外界刺激作出反应', '生物能呼吸', '生物能排出废物'], subject: '生物', topic: '生物特征' },
      { number: 11, content: '在生态系统中，能量流动的特点是', correct: false, userAnswer: 'A', correctAnswer: 'D', options: ['循环流动、逐级递增', '双向流动、逐级递减', '循环流动、逐级递减', '单向流动、逐级递减'], subject: '生物', topic: '生态系统功能' },
      { number: 12, content: '下列不属于生态系统的是', correct: true, userAnswer: 'D', correctAnswer: 'D', options: ['一片森林', '一个池塘', '一块农田', '一条鲤鱼'], subject: '生物', topic: '生态系统类型' },
      { number: 13, content: '某草原生态系统中，草→鼠→蛇→鹰，如果蛇大量减少，短期内鹰的数量会', correct: false, userAnswer: 'A', correctAnswer: 'B', options: ['增多', '减少', '不变', '先增后减'], subject: '生物', topic: '食物链与生物富集' },
      { number: 14, content: '制作洋葱表皮细胞临时装片时，滴加的液体是', correct: true, userAnswer: 'A', correctAnswer: 'A', options: ['清水', '碘液', '生理盐水', '酒精'], subject: '生物', topic: '显微镜使用' },
      { number: 15, content: '动物细胞与植物细胞都具有的结构是', correct: true, userAnswer: 'C', correctAnswer: 'C', options: ['细胞壁、细胞膜、细胞核', '细胞膜、叶绿体、细胞核', '细胞膜、细胞质、细胞核', '细胞壁、液泡、细胞核'], subject: '生物', topic: '细胞结构' },
    ]
  },
};
